version: "3.4"
services:
  removeCompletedTorrents:
    build: .
    image: ghcr.io/itsalljustdata/removecompletedtorrents
    container_name: removeCompletedTorrents
    volumes: 
      - ./my.config.yml:/app/config.yml
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: Australia/Perth
      #
      # Default Values
      #
      # PUID: 1000
      # PGID: 1000
      # LANGUAGE: en_AU.UTF8
      # TZ: Etc/UTC