
name: New Release - Publish Docker image

on:
  release:
    types: [published]
  workflow_dispatch:


jobs:
  publish:
    uses: ./.github/workflows/docker-publish.yml
    permissions:
      contents: read
      packages: write
      id-token: write
    secrets: inherit