
name: Changed Base Image - Publish Docker image

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

env:
    BASE_IMAGE: "python:3.11-slim"
  
jobs:

  check-base:

    name: Check base image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:

      - run: |
            echo "github.repository : ${{ github.repository }}"

      - name: Ensure that the image name is suitable for a docker image name
        id: IMAGE_NAME
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ github.repository }}

      - name: assign back to env
        run: |
           echo "::group::Env"
           echo IMAGE_NAME=${{ steps.IMAGE_NAME.outputs.lowercase }} >> $GITHUB_ENV
           echo "----------------------------------------------"
           echo $GITHUB_ENV 
           cat $GITHUB_ENV
           echo "----------------------------------------------"
           echo "::endgroup::"
           
    #   - name: Check out the repo
    #     uses: actions/checkout@v3.5.2

      - name: Docker Image Update Checker
        id: baseupdatecheck
        uses: lucacome/docker-image-update-checker@v1.2.1
        with:
          base-image: ${{ env.BASE_IMAGE }}
          image:  ${{ github.repository }}
          platforms: linux/amd64,linux/arm64
          #,linux/arm/v7

      - run: |
            echo "::group::Log"
            echo "github.repository : ${{ github.repository }}"
            echo "Needs Updating : ${{ steps.baseupdatecheck.outputs.needs-updating }}"
            echo "${{ steps.baseupdatecheck.output }}"
            echo "::endgroup::"
      - id: set-update
        run: echo "publish=${{ steps.baseupdatecheck.outputs.needs-updating }}" >> $GITHUB_OUTPUT

  do-publish:
    needs: check-base

    uses: ./.github/workflows/docker-publish.yml
    with:
      image-name: ${{ github.repository }}
    # secrets: inherit
    if: needs.check-base.outputs.publish == 'true'
    secrets:
      inherit